---

# Prerequisites

- name: Install Home Assistant packages
  ansible.builtin.package:
    name: '{{ home_assistant_packages }}'
    state: present
  become: true
  tags: packages

- block:
    - name: Create Home Assistant directories
      ansible.builtin.file:
        name: '{{ item.name }}'
        owner: '{{ home_assistant_daemon_user }}'
        group: '{{ home_assistant_daemon_group }}'
        mode: '{{ item.mode }}'
        state: directory
      loop:
        - { name: '{{ home_assistant_app_directory }}',        mode: '755' }
        - { name: '{{ home_assistant_app_directory }}/config', mode: '750' }
        - { name: '{{ home_assistant_log_directory }}',        mode: '755' }
  become: true
  tags: config

# Release

- block:
    # Be aware of https://bugs.python.org/issue34224
    - name: Setup Home Assistant virtualenv
      ansible.builtin.pip:
        name: [pip, wheel, setuptools]
        state: latest
        umask: '{{ home_assistant_pip_umask }}'
        virtualenv: '{{ home_assistant_app_directory }}/venv'
        virtualenv_python: '{{ home_assistant_python_executable }}'
      environment: '{{ home_assistant_pip_environment }}'

    # Be aware of https://bugs.python.org/issue34224
    - name: Install PostgreSQL client
      ansible.builtin.pip:
        name: psycopg2-binary
        state: forcereinstall
        umask: '{{ home_assistant_pip_umask }}'
        version: '{{ home_assistant_psycopg2_version }}'
        virtualenv: '{{ home_assistant_app_directory }}/venv'
        virtualenv_python: '{{ home_assistant_python_executable }}'
      environment: '{{ home_assistant_pip_environment }}'
      notify: restart home assistant

    # Be aware of https://bugs.python.org/issue34224
    - name: Install Home Assistant
      ansible.builtin.pip:
        name: homeassistant
        state: forcereinstall
        umask: '{{ home_assistant_pip_umask }}'
        version: '{{ home_assistant_version }}'
        virtualenv: '{{ home_assistant_app_directory }}/venv'
        virtualenv_python: '{{ home_assistant_python_executable }}'
      environment: '{{ home_assistant_pip_environment }}'
      notify: restart home assistant

    # See https://github.com/danielperna84/hass-configurator/wiki/Installation

    # Be aware of https://bugs.python.org/issue34224
    - name: Install Home Assistant Configurator
      ansible.builtin.pip:
        name: hass-configurator
        state: "{{ home_assistant_configurator_enabled|bool|ternary('forcereinstall', 'absent') }}"
        umask: '{{ home_assistant_pip_umask }}'
        version: '{{ home_assistant_configurator_version }}'
        virtualenv: '{{ home_assistant_app_directory }}/venv'
        virtualenv_python: '{{ home_assistant_python_executable }}'
      environment: '{{ home_assistant_pip_environment }}'
      notify: restart home assistant
  become: true
  become_user: '{{ home_assistant_daemon_user }}'
  tags: update

# Process

- block:
    - name: Configure Home Assistant service
      ansible.builtin.template:
        src: supervisor.conf.j2
        dest: /etc/supervisor/conf.d/{{ home_assistant_instance_name }}.conf
        mode: '644'
      notify: restart home assistant

    - name: Install Home Assistant service
      ansible.builtin.supervisorctl:
        name: '{{ home_assistant_instance_name }}'
        state: present
  become: true
  tags: config

- name: Start Home Assistant service
  ansible.builtin.supervisorctl:
    name: '{{ home_assistant_instance_name }}'
    state: started
  become: true
  tags: services

...
